/**
 * Output provenance (#78): a generated SVG declares ITSELF generated, so
 * tooling — the Action's orphan cleanup, editors, the Obsidian plugin — can
 * act on explicit provenance instead of name-pattern guessing. The failure
 * mode this exists to prevent is deleting a file the renderer didn't create.
 *
 * The stamp deliberately excludes timestamps and renderer versions: stamping
 * is a pure function of its inputs, so byte-identical re-renders (spec 02
 * §8.2) — and with them `verify` mode and no-op Action runs — keep working.
 */

import { esc } from "./util";

export interface Provenance {
  /** Source path, repo-relative with forward slashes. */
  source: string;
  docId: string;
  mode: string;
  /**
   * The output path this SVG was written to. A copy carried elsewhere no
   * longer matches its own location — which is exactly what protects
   * deliberately kept snapshots from cleanup.
   */
  output: string;
}

const NOTICE = "generated by chartdown - do not hand-edit";

const MARKER_RE =
  /<metadata data-chartdown-source="([^"]*)" data-chartdown-doc="([^"]*)" data-chartdown-mode="([^"]*)" data-chartdown-output="([^"]*)">[^<]*<\/metadata>/;

const unesc = (s: string): string =>
  s.replace(/&quot;/g, '"').replace(/&gt;/g, ">").replace(/&lt;/g, "<").replace(/&amp;/g, "&");

/** Insert the marker directly after the opening <svg …> tag. Idempotent: an existing marker is replaced, never doubled. */
export function stampProvenance(svg: string, p: Provenance): string {
  const marker =
    `<metadata data-chartdown-source="${esc(p.source)}" data-chartdown-doc="${esc(p.docId)}"` +
    ` data-chartdown-mode="${esc(p.mode)}" data-chartdown-output="${esc(p.output)}">${NOTICE}</metadata>`;
  const cleared = svg.replace(MARKER_RE, "");
  return cleared.replace(/^(<svg[^>]*>)/, `$1${marker}`);
}

/** The stamp a generated SVG carries, or null for anything the renderer can't vouch for. */
export function readProvenance(svg: string): Provenance | null {
  const m = MARKER_RE.exec(svg);
  return m ? { source: unesc(m[1]!), docId: unesc(m[2]!), mode: unesc(m[3]!), output: unesc(m[4]!) } : null;
}
